# Generated by Django 5.2 on 2025-04-02 16:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('industry', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='AQISubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_consumption', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fuel_type', models.CharField(max_length=20)),
                ('production_output', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('waste_emissions', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicles_operated', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('wind_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rainfall', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('aqi_score', models.FloatField()),
                ('aqi_category', models.CharField(max_length=20)),
                ('points_earned', models.IntegerField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aqi_submissions', to='core.company')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ThermalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thermal_images/')),
                ('hottest_region_x', models.IntegerField(blank=True, null=True)),
                ('hottest_region_y', models.IntegerField(blank=True, null=True)),
                ('min_temperature', models.FloatField(blank=True, null=True)),
                ('max_temperature', models.FloatField(blank=True, null=True)),
                ('thermal_category', models.CharField(max_length=20)),
                ('points_earned', models.IntegerField()),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermal_analyses', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Thermal Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
