# Generated by Django 5.2 on 2025-04-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalanalysis',
            name='heat_source_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thermalanalysis',
            name='heat_sources_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thermalanalysis',
            name='large_heat_source_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thermalanalysis',
            name='pollution_status',
            field=models.CharField(default='Non-Polluted', max_length=20),
        ),
        migrations.AddField(
            model_name='thermalanalysis',
            name='total_heat_area',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='thermalanalysis',
            name='visualization_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
