# Generated by Django 5.2 on 2025-04-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_thermalanalysis_heat_source_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermalanalysis',
            name='temp_distribution_json',
            field=models.TextField(blank=True, null=True, help_text='JSON string of temperature distribution data'),
        ),
        migrations.AddField(
            model_name='thermalanalysis',
            name='heatmap_base64',
            field=models.TextField(blank=True, null=True, help_text='Base64 of colorized heatmap'),
        ),
        migrations.AddField(
            model_name='thermalanalysis',
            name='rectangle_base64',
            field=models.TextField(blank=True, null=True, help_text='Base64 of only rectangles around heat sources'),
        ),
        migrations.AddField(
            model_name='thermalanalysis',
            name='contour_base64',
            field=models.TextField(blank=True, null=True, help_text='Base64 of contour overlay'),
        ),
    ]
